### ISSUE TITLE
VoltageMetricsReport (and others?) no longer supported in simulation.toml

### ISSUE THREAD

**Issue by nlaws-camus** [NREL/PyDSS#112]
If I understand the docs correctly, if I want the [VoltageMetricsReport](https://nrel.github.io/PyDSS/simulation_settings.html#voltagemetricsreport) then I need to add the following to my simulation.toml:
```toml
[voltagemetricsreport]
enabled = true
scenarios = ["scenario1"]
```
However, the parser does not allow for attributes not in `SimulationSettingsModel`:
```
% pydss run pydss-projects/my-project
Traceback (most recent call last):
  File "/Users/nick/projects/pydss/env/bin/pydss", line 33, in <module>
    sys.exit(load_entry_point('dsspy', 'console_scripts', 'pydss')())
  File "/Users/nick/projects/pydss/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nick/projects/pydss/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/nick/projects/pydss/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nick/projects/pydss/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nick/projects/pydss/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/nick/projects/pydss/PyDSS/PyDSS/cli/run.py", line 70, in run
    settings = PyDssProject.load_simulation_settings(project_path, simulations_file)
  File "/Users/nick/projects/pydss/PyDSS/PyDSS/pydss_project.py", line 490, in load_simulation_settings
    return load_simulation_settings(filename)
  File "/Users/nick/projects/pydss/PyDSS/PyDSS/simulation_input_models.py", line 1012, in load_simulation_settings
    settings = SimulationSettingsModel(**load_data(path))
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for SimulationSettingsModel
voltagemetricsreport
  extra fields not permitted (type=value_error.extra)
```

Do I have the simulation.toml entry correct? How do I get the VoltageMetricsReport? (Sorry if this is not really an issue but a question. Maybe open up the "Discussions" tab for things like this?).

**Comment by nlaws-camus** [comment]
I have also tried 
```toml
[reports]
format = "csv"
granularity = "per_element_per_time_point"
types = ["Voltage Metrics"]
```
based off the keys in:
https://github.com/NREL/PyDSS/blob/8a208ea5aa9d64919d60ce06854c14f1fa64eee7/PyDSS/simulation_input_models.py#L840-L848

But the logic for parsing the `types` seems to expect dictionaries?
https://github.com/NREL/PyDSS/blob/8a208ea5aa9d64919d60ce06854c14f1fa64eee7/PyDSS/simulation_input_models.py#L851-L880

**Comment by daniel-thom** [comment]
Look here for an example: https://github.com/NREL/PyDSS/blob/master/tests/data/pv_reports_project/simulation.toml#L138

**Comment by nlaws-camus** [comment]
Ok a couple things to note here:
1. it appears that the toml names are case sensitive. I had `[reports]` from the default configuration, and then adding `[[Reports.Types]]` would fail with the same error as above (`extra fields not permitted`). 
        - can fix this by either capitalizing `Reports` in both names or lower-casing `reports` in both names.
 2. I now get a `ZeroDivisionError` here: https://github.com/NREL/PyDSS/blob/8a208ea5aa9d64919d60ce06854c14f1fa64eee7/PyDSS/utils/simulation_utils.py#L32
 which is probably an issue with my openDSS model.

@daniel-thom would it make sense to have `CircularBufferHelper.average` return zero when `len(self._buf)` is zero? (If so I can PR that).

Also, are the case-sensitive names an "issue"? (I can make one with the suggested fix of adding `str.lower()` to the parsing methods).

**Comment by daniel-thom** [comment]
The pydantic models for both `reports` and `reports.types` have aliases. So, you can use combination of `reports`, `Reports`, `types`, and `Types` as long as they are all consistent. If you have `reports` and `Reports` then there will be two fields in the incoming dictionary. This could be handled by making a pydantic root_validator that pre-processes the dictionary and fixes it.

My recommendation would be that you use lower case, snake case for all fields, which is the default when you create a new project (and that's what the docs show). Everything will be simpler. When I converted the old format to use pydantic models I made this the default, but also supported backwards compatibility. That's why the test file I shared had capital letters. I didn't realize that. I should go back and convert that.

The divide by zero problem happened because the window size was 0. We should detect that and throw an error because it is non-sensical.

**Comment by nlaws-camus** [comment]
> The divide by zero problem happened because the window size was 0. We should detect that and throw an error because it is non-sensical.

I noticed some handling in the average method already so I added to it:
https://github.com/NREL/PyDSS/pull/113
