### ISSUE TITLE
OpenDSS-HELICS Integration

### ISSUE THREAD

**Issue by AmitHREDIITR** [NREL/PyDSS#122]
Hello 
I am working to integrate OpenDSS with HELICS on Linux Platform.
First, I install OpenDSSdirect.py in linux environment. HELICS already installed in my linux platform. Now please advise how i can run opendss examples and how it can be called in HELICS.

**Comment by AadilLatif** [comment]
PyDSS installs helics as a dependency. see https://nrel.github.io/PyDSS/index.html for installation
