### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by asavasci** [NREL/PyDSS#37]
Hello, I am using following method to install PyDSS, 
pip install -i https://test.pypi.org/simple/ PyDSS==0.0.1

However, I am getting the error prompt as 
ERROR: Could not find a version that satisfies the requirement scipy==1.2.1 (from PyDSS==0.0.1) (from versions: 0.1)
ERROR: No matching distribution found for scipy==1.2.1 (from PyDSS==0.0.1)

**Comment by AadilLatif** [comment]
The documentation needs to be updated. I would recommend cloning the repo. In a terminal use go to the folder with the setup.py file. here type 'python setup.py install'. If you are a developer, you can use 'pip install -e.' instead.
