### ISSUE TITLE
pip install issues with `tables`

### ISSUE THREAD

**Issue by bpalmintier** [NREL/PyDSS#80]
When I went to pip install pydss into a new (conda) environment it seems to be having troubles with the `tables` package.

What seems to be happening is that pip tries a bunch of different versions of tables but none work . The Final Error:
```
ERROR: Could not find a version that satisfies the requirement tables (from dsspy) (from versions: 2.3, 2.3.1, 2.4.0, 3.0.0, 3.1.0, 3.1.1, 3.2.0rc1, 3.2.0rc2, 3.2.0, 3.2.1.1, 3.2.2, 3.2.3, 3.2.3.1, 3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5.1, 3.5.2, 3.6.1)
ERROR: No matching distribution found for tables
```

The specific issue varies by version tried, but here are a few (full details in attached [log](https://github.com/NREL/PyDSS/files/7269761/PyDSS.install.error-tables.txt)):
* 3.6.1: could not HDF5 not found
* 3.2.3: ModuleNotFoundError: No module named 'cpuinfo'
* 3.1.1: ERROR:: You need numpy 1.4.1 or greater to run PyTables!

To recreate:
1. Make new environment (I used the latest conda and python=3, which defaulted to python 3.9.7)
2. Clone PyDSS to a folder
3. From folder run `pip install -e .` (per #37, since documentation still seems to be out of date)
4. (Error occurs)

**Comment by daniel-thom** [comment]
The latest Python version currently supported is 3.7 because we are still using an old version of OpenDSSDirect. This _might_ make this issue go away. Can you try it?

**Comment by bpalmintier** [comment]
Yes! That seems to have done it... the pip install now fully completes. Reverting to Python 3.7 did the trick.
